version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration: RelWithDebInfo
clone_folder: c:\local\source
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  BUGSPLAT_USERNAME: ilya77@gmail.com
  BUGSPLAT_PASSWORD:
    secure: 9c6LeJtXAXvISt7o1o5lnw==
install:
- cmd: >-
    if not exist c:\local md c:\local

    cinst -y git

    cinst -y cmake

    cinst -y curl

    git clone --recursive https://github.com/jp9000/obs-studio.git c:\local\obs-studio

    cd /d c:\local\obs-studio\plugins

    md obs-streamelements-core

    xcopy c:\local\source\*.* c:\local\obs-studio\plugins\obs-streamelements-core /S /E /I /Y

    echo add_subdirectory(obs-streamelements-core) >c:\local\obs-studio\plugins\CMakeLists.txt

cache:
- c:\local\obs-build-dependencies

build_script:
- cmd: >-
    echo ("#define STREAMELEMENTS_PLUGIN_VERSION " + (Get-Date).ToUniversalTime().ToString("yyyyMMdd") + "${Env:APPVEYOR_BUILD_NUMBER}".PadLeft(6, '0')) >c:\local\generate_version.ps1

    echo ("set STREAMELEMENTS_PLUGIN_VERSION=" + (Get-Date).ToUniversalTime().ToString("y.M.d") + "." + "${Env:APPVEYOR_BUILD_NUMBER}".PadLeft(1, '0')) >c:\local\generate_version_cmd.ps1

    powershell -File c:\local\generate_version.ps1 >c:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp

    powershell -File c:\local\generate_version_cmd.ps1 >c:\local\generate_version_cmd.bat

    c:\local\generate_version_cmd.bat

    echo %STREAMELEMENTS_PLUGIN_VERSION%

    cd /d c:\local\obs-studio

- ps: >-
    CI\build-windows.ps1 -CombinedArchs -BuildConfiguration RelWithDebInfo

- cmd: >-
    echo.Upload PDBs to BugSplat in case this is a commit to master branch.

    if "%APPVEYOR_PULL_REQUEST_HEAD_COMMIT%"=="" c:\local\obs-studio\plugins\obs-streamelements-core\deps\BugSplat\bin\SendPdbs.exe /u "%BUGSPLAT_USERNAME%" /p "%BUGSPLAT_PASSWORD%" /a obs-streamelements-core /v "%STREAMELEMENTS_PLUGIN_VERSION%" /b OBS_Live /d "c:\local\obs-studio\build64\rundir\RelWithDebInfo\obs-plugins\64bit" /f obs-streamelements-core.pdb

    if "%APPVEYOR_PULL_REQUEST_HEAD_COMMIT%"=="" c:\local\obs-studio\plugins\obs-streamelements-core\deps\BugSplat\bin\SendPdbs.exe /u "%BUGSPLAT_USERNAME%" /p "%BUGSPLAT_PASSWORD%" /a obs-streamelements-core /v "%STREAMELEMENTS_PLUGIN_VERSION%" /b OBS_Live /d "c:\local\obs-studio\build32\rundir\RelWithDebInfo\obs-plugins\64bit" /f obs-streamelements-core.pdb



    echo.===================== PACK ARTIFACTS =====================

    echo.Pack 64bit artifacts...

    cd /d c:\local\obs-studio\build64\rundir\RelWithDebInfo

    7z a c:\local\source\build64.zip .



    echo.Pack 32bit artifacts...

    cd /d c:\local\obs-studio\build32\rundir\RelWithDebInfo

    7z a c:\local\source\build32.zip .



    echo.Update generated version header...

    copy /Y c:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp c:\local\source\streamelements\Version.generated.hpp
test: off
artifacts:
- path: build32.zip
  name: build32
- path: build64.zip
  name: build64
- path: streamelements\Version.generated.hpp
  name: version.generated.hpp
deploy:
- provider: S3
  access_key_id: AKIAJESHQW2DGHPN57KQ
  secret_access_key:
    secure: lhOyqT4/E0Oqv8BOQR81rx/SweOIbDELTYW7iJTqRz5shmkZ8eXMCgFzcIuXyvpB
  bucket: obs-builds
  folder: obs-streamelements-core/latest/windows
  artifact: build32,build64,version.generated.hpp
  max_error_retry: 5
  on:
    branch: master
on_success:
- cmd: echo.All done.
