version: '{build}'
branches:
  only:
  - master
  - qt6
image: Visual Studio 2022
configuration: RelWithDebInfo
clone_folder: c:\local\source
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  BUGSPLAT_USERNAME: ilya77@gmail.com
  BUGSPLAT_PASSWORD:
    secure: 9c6LeJtXAXvISt7o1o5lnw==
install:
- cmd: >-
    if not exist c:\local md c:\local

    git clone --recursive https://github.com/jp9000/obs-studio.git c:\local\obs-studio

    cd /d c:\local\obs-studio

    git checkout 5fd4339c1d32f57e0e510881e1321cb8c3b5f1ba

    cd /d c:\local\obs-studio\plugins

    md obs-streamelements-core

    xcopy c:\local\source\*.* c:\local\obs-studio\plugins\obs-streamelements-core /S /E /I /Y

    echo add_subdirectory(obs-streamelements-core) >c:\local\obs-studio\plugins\CMakeLists.txt

cache:
- c:\local\obs-build-dependencies

build_script:
- cmd: >-
    echo ("#define STREAMELEMENTS_PLUGIN_VERSION " + (Get-Date).ToUniversalTime().ToString("yyyyMMdd") + "${Env:APPVEYOR_BUILD_NUMBER}".PadLeft(6, '0')) >c:\local\generate_version.ps1

    echo ("set STREAMELEMENTS_PLUGIN_VERSION=" + (Get-Date).ToUniversalTime().ToString("y.M.d") + "." + "${Env:APPVEYOR_BUILD_NUMBER}".PadLeft(1, '0')) >c:\local\generate_version_cmd.ps1

    powershell -File c:\local\generate_version.ps1 >c:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp

    powershell -File c:\local\generate_version_cmd.ps1 >c:\local\generate_version_cmd.bat

    c:\local\generate_version_cmd.bat

    echo %STREAMELEMENTS_PLUGIN_VERSION%

    cd /d c:\local\obs-studio

- ps: >-
    .\CI\windows\01_install_dependencies.ps1 -Verbose -BuildArch x64

    .\CI\windows\01_install_dependencies.ps1 -Verbose -BuildArch x86

- ps: >-
    $CmakeCommand = @(
      "-S . -B `"build64`"",
      "-G `"Visual Studio 17 2022`"",
      "-DCMAKE_GENERATOR_PLATFORM=`"x64`"",
      "-DCMAKE_SYSTEM_VERSION=`"10.0.22000.0`"",
      "-DCMAKE_PREFIX_PATH=`"build64`"",
      "-DCEF_ROOT_DIR=`"c:/local/obs-build-dependencies/cef_binary_4638_windows_x64`"",
      "-DVLC_PATH=`"c:/local/obs-build-dependencies/vlc-3.0.0-git`"",
      "-DCMAKE_INSTALL_PREFIX=`"build64/install`"",
      "-DCOPIED_DEPENDENCIES=OFF",
      "-DCOPY_DEPENDENCIES=ON",
      "-DBUILD_FOR_DISTRIBUTION=`"OFF`"",
      "-DDepsPath64=c:/local/obs-build-dependencies/windows-deps-2022-05-23-x64",
      "-Wno-error=dev -Wno-dev -Wno-deprecated",
      "-DENABLE_AJA=OFF",
      "-DENABLE_BROWSER=OFF",
      "-DENABLE_COREAUDIO_ENCODER=OFF",
      "-DENABLE_DECKLINK=OFF",
      "-DENABLE_FFMPEG_LOGGING=OFF",
      "-DENABLE_FFMPEG_MUX_DEBUG=OFF",
      "-DENABLE_FREETYPE=OFF",
      "-DENABLE_HEVC=OFF",
      "-DENABLE_IVCAM=OFF",
      "-DENABLE_LIBFDK=OFF",
      "-DENABLE_NVAFX=OFF",
      "-DENABLE_QSV11=OFF",
      "-DENABLE_RNNOISE=OFF",
      "-DENABLE_RTMPS=OFF",
      "-DENABLE_SCRIPTING=OFF",
      "-DENABLE_SCRIPTING_LUA=OFF",
      "-DENABLE_SCRIPTING_PYTHON=OFF",
      "-DENABLE_SERVICE_UPDATES=OFF",
      "-DENABLE_SIMDE=OFF",
      "-DENABLE_SPEEXDSP=OFF",
      "-DENABLE_UI=OFF",
      "-DENABLE_UPDATER=OFF",
      "-DENABLE_VIRTUALCAM=OFF",
      "-DENABLE_VLC=OFF",
      "-DENABLE_VST=OFF",
      "-DQTDIR=C:\Qt\5.15.2",
      "-DVIRTUALCAM_GUID=`"A3FCE0F5-3493-419F-958A-ABA1250EC20B`"",
      "-DTHREADS_HAVE_PTHREAD_ARG=OFF"
    )

    Invoke-Expression "cmake ${CmakeCommand}"

    Invoke-Expression "cmake --build build64 --config RelWithDebInfo"

- ps: >-
    $CmakeCommand = @(
      "-S . -B `"build32`"",
      "-G `"Visual Studio 17 2022`"",
      "-DCMAKE_GENERATOR_PLATFORM=`"Win32`"",
      "-DCMAKE_SYSTEM_VERSION=`"10.0.22000.0`"",
      "-DCMAKE_PREFIX_PATH=`"build32`"",
      "-DCEF_ROOT_DIR=`"c:/local/obs-build-dependencies/cef_binary_4638_windows_x86`"",
      "-DVLC_PATH=`"c:/local/obs-build-dependencies/vlc-3.0.0-git`"",
      "-DCMAKE_INSTALL_PREFIX=`"build32/install`"",
      "-DCOPIED_DEPENDENCIES=OFF",
      "-DCOPY_DEPENDENCIES=ON",
      "-DBUILD_FOR_DISTRIBUTION=`"OFF`"",
      "-DDepsPath32=c:/local/obs-build-dependencies/windows-deps-2022-05-23-x86",
      "-Wno-error=dev -Wno-dev -Wno-deprecated",
      "-DENABLE_AJA=OFF",
      "-DENABLE_BROWSER=OFF",
      "-DENABLE_COREAUDIO_ENCODER=OFF",
      "-DENABLE_DECKLINK=OFF",
      "-DENABLE_FFMPEG_LOGGING=OFF",
      "-DENABLE_FFMPEG_MUX_DEBUG=OFF",
      "-DENABLE_FREETYPE=OFF",
      "-DENABLE_HEVC=OFF",
      "-DENABLE_IVCAM=OFF",
      "-DENABLE_LIBFDK=OFF",
      "-DENABLE_NVAFX=OFF",
      "-DENABLE_QSV11=OFF",
      "-DENABLE_RNNOISE=OFF",
      "-DENABLE_RTMPS=OFF",
      "-DENABLE_SCRIPTING=OFF",
      "-DENABLE_SCRIPTING_LUA=OFF",
      "-DENABLE_SCRIPTING_PYTHON=OFF",
      "-DENABLE_SERVICE_UPDATES=OFF",
      "-DENABLE_SIMDE=OFF",
      "-DENABLE_SPEEXDSP=OFF",
      "-DENABLE_UI=OFF",
      "-DENABLE_UPDATER=OFF",
      "-DENABLE_VIRTUALCAM=OFF",
      "-DENABLE_VLC=OFF",
      "-DENABLE_VST=OFF",
      "-DQTDIR=C:\Qt\5.15.2",
      "-DVIRTUALCAM_GUID=`"A3FCE0F5-3493-419F-958A-ABA1250EC20B`"",
      "-DTHREADS_HAVE_PTHREAD_ARG=OFF"
    )

    Invoke-Expression "cmake ${CmakeCommand}"

    Invoke-Expression "cmake --build build32 --config RelWithDebInfo"

- cmd: >-
    echo.Upload PDBs to BugSplat in case this is a commit to master branch.

    if "%APPVEYOR_PULL_REQUEST_HEAD_COMMIT%"=="" c:\local\obs-studio\plugins\obs-streamelements-core\deps\BugSplat\bin\SendPdbs.exe /u "%BUGSPLAT_USERNAME%" /p "%BUGSPLAT_PASSWORD%" /a obs-streamelements-core /v "%STREAMELEMENTS_PLUGIN_VERSION%" /b OBS_Live /d "c:\local\obs-studio\build64\rundir\RelWithDebInfo\obs-plugins\64bit" /f obs-streamelements-core.pdb

    if "%APPVEYOR_PULL_REQUEST_HEAD_COMMIT%"=="" c:\local\obs-studio\plugins\obs-streamelements-core\deps\BugSplat\bin\SendPdbs.exe /u "%BUGSPLAT_USERNAME%" /p "%BUGSPLAT_PASSWORD%" /a obs-streamelements-core /v "%STREAMELEMENTS_PLUGIN_VERSION%" /b OBS_Live /d "c:\local\obs-studio\build32\rundir\RelWithDebInfo\obs-plugins\32bit" /f obs-streamelements-core.pdb



    echo.===================== PACK ARTIFACTS =====================

    echo.Pack 64bit artifacts...

    cd /d c:\local\obs-studio\build64\rundir\RelWithDebInfo

    7z a c:\local\source\build64.zip .



    echo.Pack 32bit artifacts...

    cd /d c:\local\obs-studio\build32\rundir\RelWithDebInfo

    7z a c:\local\source\build32.zip .



    echo.Update generated version header...

    copy /Y c:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp c:\local\source\streamelements\Version.generated.hpp
test: off
artifacts:
- path: build32.zip
  name: build32
- path: build64.zip
  name: build64
- path: streamelements\Version.generated.hpp
  name: version.generated.hpp
deploy:
- provider: S3
  access_key_id: AKIAJESHQW2DGHPN57KQ
  secret_access_key:
    secure: lhOyqT4/E0Oqv8BOQR81rx/SweOIbDELTYW7iJTqRz5shmkZ8eXMCgFzcIuXyvpB
  bucket: obs-builds
  folder: obs-streamelements-core/latest/windows
  artifact: build32,build64,version.generated.hpp
  max_error_retry: 5
  on:
    branch: master
on_success:
- cmd: echo.All done.
