name: Build

permissions:
  contents: read
  id-token: write    # lets the job mint a GitHub OIDC token for WIF

on:
  workflow_call:

env:
  ROOT: ${{ github.workspace }}\CI\obs-streamelements-uninstaller

  SIGN_BINARIES: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
  UPLOAD_BINARIES: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}

jobs:
  build-uninstaller-windows:
    runs-on: windows-2022

    steps:
      - name: Debug
        shell: cmd
        run: |
          echo "${{ github.event.repository.updated_at }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth Google API
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: streamelements-core
          workload_identity_provider: ${{ vars.GCS_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ vars.GCS_SERVICE_ACCOUNT }}

      - name: Generate build number
        uses: mlilback/build-number@v1
        with:
          base: ${{ env.BASE_BUILD_NUMBER }}
          run-id: ${{ github.run_number }}
          # Output: ${{ env.BUILD_NUMBER }} env var

      - name: Install Chocolatey packages
        shell: cmd
        run: |
          choco install -y archiver
          choco install -y nsis --version=3.03 --force

      - name: Download resources
        shell: cmd
        run: |
          cd /d "${{ env.ROOT }}"

          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/obs-probe-libobs-version/windows/qa/obs-probe-libobs-version-32.exe --output resources\obs-probe-libobs-version-32.exe
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/obs-probe-libobs-version/windows/qa/obs-probe-libobs-version-64.exe --output resources\obs-probe-libobs-version-64.exe

      - name: Install NSIS plugins
        shell: cmd
        run: |
          cd /d "${{ env.ROOT }}"

          if exist nsis\Plugins\x64-ansi\NSISLockDetector.dll del nsis\Plugins\x64-ansi\NSISLockDetector.dll
          if exist nsis\Plugins\x64-unicode\NSISLockDetector.dll del nsis\Plugins\x64-unicode\NSISLockDetector.dll
          if exist nsis\Plugins\x86-ansi\NSISLockDetector.dll del nsis\Plugins\x86-ansi\NSISLockDetector.dll
          if exist nsis\Plugins\x86-unicode\NSISLockDetector.dll del nsis\Plugins\x86-unicode\NSISLockDetector.dll

          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-lockdetector/windows/qa/x64-ansi/NSISLockDetector.dll --output nsis\Plugins\x64-ansi\NSISLockDetector.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-lockdetector/windows/qa/x64-unicode/NSISLockDetector.dll --output nsis\Plugins\x64-unicode\NSISLockDetector.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-lockdetector/windows/qa/x86-ansi/NSISLockDetector.dll --output nsis\Plugins\x86-ansi\NSISLockDetector.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-lockdetector/windows/qa/x86-unicode/NSISLockDetector.dll --output nsis\Plugins\x86-unicode\NSISLockDetector.dll

          if exist nsis\Plugins\x64-ansi\NSISHTTP.dll del nsis\Plugins\x64-ansi\NSISHTTP.dll
          if exist nsis\Plugins\x64-unicode\NSISHTTP.dll del nsis\Plugins\x64-unicode\NSISHTTP.dll
          if exist nsis\Plugins\x86-ansi\NSISHTTP.dll del nsis\Plugins\x86-ansi\NSISHTTP.dll
          if exist nsis\Plugins\x86-unicode\NSISHTTP.dll del nsis\Plugins\x86-unicode\NSISHTTP.dll

          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-http/windows/qa/x64-ansi/NSISHTTP.dll --output nsis\Plugins\x64-ansi\NSISHTTP.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-http/windows/qa/x64-unicode/NSISHTTP.dll --output nsis\Plugins\x64-unicode\NSISHTTP.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-http/windows/qa/x86-ansi/NSISHTTP.dll --output nsis\Plugins\x86-ansi\NSISHTTP.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-http/windows/qa/x86-unicode/NSISHTTP.dll --output nsis\Plugins\x86-unicode\NSISHTTP.dll

          if exist nsis\Plugins\x64-ansi\NSISConfig.dll del nsis\Plugins\x64-ansi\NSISConfig.dll
          if exist nsis\Plugins\x64-unicode\NSISConfig.dll del nsis\Plugins\x64-unicode\NSISConfig.dll
          if exist nsis\Plugins\x86-ansi\NSISConfig.dll del nsis\Plugins\x86-ansi\NSISConfig.dll
          if exist nsis\Plugins\x86-unicode\NSISConfig.dll del nsis\Plugins\x86-unicode\NSISConfig.dll

          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-config/windows/qa/x64-ansi/NSISConfig.dll --output nsis\Plugins\x64-ansi\NSISConfig.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-config/windows/qa/x64-unicode/NSISConfig.dll --output nsis\Plugins\x64-unicode\NSISConfig.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-config/windows/qa/x86-ansi/NSISConfig.dll --output nsis\Plugins\x86-ansi\NSISConfig.dll
          curl -L https://storage.googleapis.com/cdn.streamelements.com/obs/dist/nsis-config/windows/qa/x86-unicode/NSISConfig.dll --output nsis\Plugins\x86-unicode\NSISConfig.dll

          xcopy nsis "%ProgramFiles(x86)%\NSIS" /S /E /I /Y

      - name: Build installer
        shell: cmd
        run: |
          cd /d "${{ env.ROOT }}"

          makensis /V4 main.nsi

      - name: Sign Windows binaries
        uses: azure/artifact-signing-action@v2
        if: ${{ env.SIGN_BINARIES }}
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://eus.codesigning.azure.net/
          signing-account-name: SE-Live
          certificate-profile-name: SE-Live
          files-folder: '${{ env.ROOT }}'
          files-folder-filter: exe,dll,msi
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

# Automatically finds signtool.exe and exposes its path
      - name: Find SignTool
        if: ${{ env.SIGN_BINARIES }}
        uses: KamaranL/add-signtool-action@v1
        id: signtool

      - name: Verify Windows binaries code signature
        if: ${{ env.SIGN_BINARIES }}
        shell: cmd
        run: |
          signtool verify /pa /v "${{ env.ROOT }}\\obs-streamelements-uninstaller.exe"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: uninstaller
          path: obs-streamelements-uninstaller.exe

      - name: Upload to Google Artifact Storage
        if: ${{ env.UPLOAD_BINARIES }}
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ env.ROOT }}/obs-streamelements-uninstaller.exe'
          destination: 'se-obs-builds/obs-streamelements-uninstaller/latest/windows'

      - name: Upload to CDN Signed Artifact Storage
        if: ${{ env.UPLOAD_BINARIES }}
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ env.ROOT }}/obs-streamelements-uninstaller.exe'
          destination: 'cdn.streamelements.com/obs/dist/obs-streamelements-uninstaller/windows/signed'

      - name: Upload to CDN QA Artifact Storage
        if: ${{ env.UPLOAD_BINARIES }}
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ env.ROOT }}/obs-streamelements-uninstaller.exe'
          destination: 'cdn.streamelements.com/obs/dist/obs-streamelements-uninstaller/windows/qa'

      - name: Upload to CDN Latest Artifact Storage
        if: ${{ env.UPLOAD_BINARIES }}
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ env.ROOT }}/obs-streamelements-uninstaller.exe'
          destination: 'cdn.streamelements.com/obs/dist/obs-streamelements-uninstaller/windows/latest'
