name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  BASE_BUILD_NUMBER: 569

  BUILD_OPTIONS: >
    -DENABLE_DECKLINK=OFF
    -DENABLE_SYPHON=OFF
    -DENABLE_LIBFDK=OFF
    -DENABLE_NVENC=OFF
    -DENABLE_QSV11=OFF
    -DENABLE_VST=OFF
    -DENABLE_WEBRTC=OFF
    -DENABLE_WEBSOCKET=OFF
    -DENABLE_OSS=OFF
    -DENABLE_SNDIO=OFF
    -DENABLE_VLC=OFF
    -DENABLE_VIRTUALCAM=OFF
    -DENABLE_TEST_INPUT=OFF
    -DENABLE_AJA=OFF
    -DENABLE_SCRIPTING=OFF
    -DENABLE_SCRIPTING_LUA=OFF
    -DENABLE_UI=OFF

jobs:
  windows:
    runs-on: windows-2022

    env:
      CHECKOUT: 31.1.2
      GS_ACCESS_KEY_ID: ${{ secrets.GS_ACCESS_KEY_ID }}
      GS_SECRET_ACCESS_KEY: ${{ secrets.GS_SECRET_ACCESS_KEY }}
      GS_KEY_BASE64: ${{ secrets.GS_KEY_BASE64 }}

    steps:
      - name: Auth Google API
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: streamelements-core
          workload_identity_provider: ${{ vars.GCS_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ vars.GCS_SERVICE_ACCOUNT }}

      - uses: actions/checkout@v4

      - name: Generate build number
        uses: mlilback/build-number@v1
        with:
          base: ${{ env.BASE_BUILD_NUMBER }}
          run-id: ${{ github.run_number }}
          # Output: ${{ env.BUILD_NUMBER }} env var

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Clone OBS Studio
        shell: cmd
        run: |
          mkdir C:\local
          git clone --recursive https://github.com/obsproject/obs-studio.git C:\local\obs-studio
          cd /d C:\local\obs-studio
          git checkout %CHECKOUT%

      - name: Install plugin into OBS tree
        shell: cmd
        run: |
          mkdir C:\local\obs-studio\plugins\obs-streamelements-core
          xcopy "%GITHUB_WORKSPACE%\*.*" "C:\local\obs-studio\plugins\obs-streamelements-core" /S /E /I /Y
          echo add_obs_plugin(obs-streamelements-core) > C:\local\obs-studio\plugins\CMakeLists.txt

      - name: Setup GCS uploader
        shell: powershell
        run: |
          cd C:\local\obs-studio\plugins\obs-streamelements-core\CI\gcs
          [System.Text.Encoding]::UTF8.GetString(
            [System.Convert]::FromBase64String($env:GS_KEY_BASE64)
          ) | Out-File key.json
          npm install

      - name: Download BugSplat uploader
        run: |
          mkdir c:\local\bugsplat

          c:

          cd c:\local\bugsplat

          curl -sL -O https://github.com/BugSplat-Git/symbol-upload/releases/download/v10.5.0/symbol-upload-windows.exe

      - name: Generate Version
        shell: powershell
        run: |
          echo BUILD_NUMBER=${{ env.BUILD_NUMBER }}

          $versionInt = (Get-Date).ToUniversalTime().ToString("yyyyMMdd") +
            "${{ env.BUILD_NUMBER }}".PadLeft(6,'0')

          "#define STREAMELEMENTS_PLUGIN_VERSION $versionInt" |
            Out-File C:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp

          type C:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp

          $versionStr = (Get-Date).ToUniversalTime().ToString("y.M.d") +
            ".${{ env.BUILD_NUMBER }}"

          "STREAMELEMENTS_PLUGIN_VERSION=$versionStr" |
            Out-File $env:GITHUB_ENV -Append

      - name: Configure
        shell: cmd
        run: |
          copy C:\local\obs-studio\plugins\obs-streamelements-core\CMakeUserPresets.json C:\local\obs-studio\CMakeUserPresets.json
          del C:\local\obs-studio\plugins\obs-streamelements-core\CMakeUserPresets.json
          cd /d C:\local\obs-studio
          cmake --preset=windows-x64-streamelements %BUILD_OPTIONS%

      - name: Build
        shell: cmd
        run: |
          cd /d C:\local\obs-studio\build_x64
          msbuild obs-studio.sln -p:Configuration=RelWithDebInfo

      - name: Upload BugSplat Symbols
        if: github.event_name != 'pull_request'
        shell: cmd
        run: |
          c:\local\bugsplat\symbol-upload-windows.exe ^
            -v ^
            --clientId "${{ secrets.BUGSPLAT_CLIENTID }}" ^
            --clientSecret "${{ secrets.BUGSPLAT_CLIENTSECRET }}" ^
            --application obs-streamelements-core ^
            --version "${{ env.STREAMELEMENTS_PLUGIN_VERSION }}" ^
            --database OBS_Live ^
            --directory "C:\local\obs-studio\build_x64\rundir\RelWithDebInfo\obs-plugins\64bit" ^
            --files obs-streamelements*.pdb

      - name: Package
        shell: cmd
        run: |
          cd /d C:\local\obs-studio\build_x64\rundir\RelWithDebInfo
          7z a %GITHUB_WORKSPACE%\build64_qt6.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: build64
          path: build64_qt6.zip

      - name: Upload to GCS
        if: github.event_name != 'pull_request'
        shell: cmd
        run: |
          cd /d C:\local\obs-studio\plugins\obs-streamelements-core\CI\gcs
          node upload.js %GITHUB_WORKSPACE%\build64_qt6.zip se-obs-builds obs-streamelements-core/latest/windows/build64_qt6.zip
          node upload.js C:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp se-obs-builds obs-streamelements-core/latest/windows/Version.generated.hpp

  macos:
    runs-on: macos-15

    env:
      CHECKOUT: 31.1.2
      GS_ACCESS_KEY_ID: ${{ secrets.GS_ACCESS_KEY_ID }}
      GS_SECRET_ACCESS_KEY: ${{ secrets.GS_SECRET_ACCESS_KEY }}

    steps:
      - name: Auth Google API
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: streamelements-core
          workload_identity_provider: ${{ vars.GCS_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ vars.GCS_SERVICE_ACCOUNT }}

      - uses: actions/checkout@v4

      - name: Generate build number
        uses: mlilback/build-number@v1
        with:
          base: ${{ env.BASE_BUILD_NUMBER }}
          run-id: ${{ github.run_number }}
          # Output: ${{ env.BASE_BUILD_NUMBER }} env var

      - name: Clone OBS Studio
        run: |
          git clone --recursive https://github.com/obsproject/obs-studio.git ~/src/obs-studio
          cd ~/src/obs-studio
          git checkout $CHECKOUT

      - name: Install plugin
        run: |
          cp -R "$GITHUB_WORKSPACE" ~/src/obs-studio/plugins/obs-streamelements-core
          echo "add_obs_plugin(obs-streamelements-core)" >> ~/src/obs-studio/plugins/CMakeLists.txt

      - name: Prepare bugsplat Framework # we store it as a ZIP since on Windows the resulting paths of the unpacked archive are just way too long
        run: |
          cd ~/src/obs-studio/plugins/obs-streamelements-core/deps

          unzip BugSplat.xcframework.zip

      - name: Download BugSplat uploader
        run: |
          cd /tmp
          curl -sL -O https://github.com/BugSplat-Git/symbol-upload/releases/download/v10.5.0/symbol-upload-macos
          #cp symbol-upload-macos-intel symbol-upload-macos
          chmod +x symbol-upload-macos

      - name: Generate Version
        run: |
          echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}"

          VERSION="$(date '+%Y%m%d')$(printf '%06d' ${{ env.BUILD_NUMBER }})"

          echo "#define STREAMELEMENTS_PLUGIN_VERSION $VERSION" \
            > ~/src/obs-studio/plugins/obs-streamelements-core/streamelements/Version.generated.hpp

          cat ~/src/obs-studio/plugins/obs-streamelements-core/streamelements/Version.generated.hpp

          echo "STREAMELEMENTS_PLUGIN_VERSION_FULL=$VERSION" >> $GITHUB_ENV

      - name: Debug Bugsplat Input
        run: |
          echo "Client ID length:"
          
          echo "${{ secrets.BUGSPLAT_CLIENTID }}" |wc -c
          
          echo "Client Secret length:"

          echo "${{ secrets.BUGSPLAT_CLIENTSECRET }}" |wc -c

      - name: Build ARM64
        run: |
          cd ~/src/obs-studio
          cmake --preset=macos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -B build_macos_arm64 \
            $BUILD_OPTIONS

          cd build_macos_arm64

          xcodebuild \
            -configuration RelWithDebInfo \
            -scheme obs-streamelements-core \
            -destination "generic/platform=macOS,name=Any Mac"

          cd ~/src/obs-studio/build_macos_arm64/plugins/obs-streamelements-core/RelWithDebInfo

          xcrun dsymutil obs-streamelements-core.plugin/Contents/MacOS/obs-streamelements-core -o obs-streamelements-core.dSYM

      - name: Upload ARM64 to BugSplat
        if: github.event_name != 'pull_request'
        run: |
          cd ~/src/obs-studio/build_macos_arm64/plugins/obs-streamelements-core/RelWithDebInfo

          /tmp/symbol-upload-macos -v -a "obs-streamelements-core-macos" -b "OBS_Live" -i "${{ secrets.BUGSPLAT_CLIENTID }}" -s "${{ secrets.BUGSPLAT_CLIENTSECRET }}" -f "obs-streamelements-core.dSYM" -d . -v "${{ env.STREAMELEMENTS_PLUGIN_VERSION_FULL }}"
      - name: Build x86_64
        run: |
          cd ~/src/obs-studio
          cmake --preset=macos \
            -DCMAKE_OSX_ARCHITECTURES=x86_64 \
            -B build_macos_x86_64 \
            $BUILD_OPTIONS

          cd build_macos_x86_64
          xcodebuild \
            -configuration RelWithDebInfo \
            -scheme obs-streamelements-core \
            -destination "generic/platform=macOS,name=Any Mac"

          cd ~/src/obs-studio/build_macos_x86_64/plugins/obs-streamelements-core/RelWithDebInfo

          xcrun dsymutil obs-streamelements-core.plugin/Contents/MacOS/obs-streamelements-core -o obs-streamelements-core.dSYM

      - name: Upload x86_64 to BugSplat
        if: github.event_name != 'pull_request'
        run: |
          cd ~/src/obs-studio/build_macos_x86_64/plugins/obs-streamelements-core/RelWithDebInfo

          /tmp/symbol-upload-macos -v -a "obs-streamelements-core-macos" -b "OBS_Live" -i "${{ secrets.BUGSPLAT_CLIENTID }}" -s "${{ secrets.BUGSPLAT_CLIENTSECRET }}" -f "obs-streamelements-core.dSYM" -d . -v "${{ env.STREAMELEMENTS_PLUGIN_VERSION_FULL }}"
      - name: Package
        run: |
          cd ~/src/obs-studio/build_macos_arm64/plugins/obs-streamelements-core/RelWithDebInfo
          7z a $GITHUB_WORKSPACE/build_arm64.zip .

          cd ~/src/obs-studio/build_macos_x86_64/plugins/obs-streamelements-core/RelWithDebInfo
          7z a $GITHUB_WORKSPACE/build_x86_64.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: macos-builds
          path: |
            build_arm64.zip
            build_x86_64.zip
      - name: Upload to GCS
        if: github.event_name != 'pull_request'
        run: |
          curl https://sdk.cloud.google.com > install-google-cloud-sdk.sh
          bash install-google-cloud-sdk.sh --disable-prompts

          cat > ~/.boto <<EOF
          [Credentials]
          gs_access_key_id = $GS_ACCESS_KEY_ID
          gs_secret_access_key = $GS_SECRET_ACCESS_KEY
          EOF

          ~/google-cloud-sdk/bin/gsutil cp build_x86_64.zip gs://se-obs-builds/obs-streamelements-core/latest/macos/build_x86_64.zip
          ~/google-cloud-sdk/bin/gsutil cp build_arm64.zip gs://se-obs-builds/obs-streamelements-core/latest/macos/build_arm64.zip
          ~/google-cloud-sdk/bin/gsutil cp ~/src/obs-studio/plugins/obs-streamelements-core/streamelements/Version.generated.hpp gs://se-obs-builds/obs-streamelements-core/latest/macos/Version.generated.hpp
