name: Build

permissions:
  contents: write    # lets GITHUB_TOKEN push tags
  id-token: write    # lets the job mint a GitHub OIDC token for WIF
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

env:
  BASE_BUILD_NUMBER: 569

  BUILD_OPTIONS: >
    -DENABLE_DECKLINK=OFF
    -DENABLE_SYPHON=OFF
    -DENABLE_LIBFDK=OFF
    -DENABLE_NVENC=OFF
    -DENABLE_QSV11=OFF
    -DENABLE_VST=OFF
    -DENABLE_WEBRTC=OFF
    -DENABLE_WEBSOCKET=OFF
    -DENABLE_OSS=OFF
    -DENABLE_SNDIO=OFF
    -DENABLE_VLC=OFF
    -DENABLE_VIRTUALCAM=OFF
    -DENABLE_TEST_INPUT=OFF
    -DENABLE_AJA=OFF
    -DENABLE_SCRIPTING=OFF
    -DENABLE_SCRIPTING_LUA=OFF
    -DENABLE_UI=OFF

  BUILD_UNINSTALLER: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
  BUILD_INSTALLER: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
  UPLOAD_SYMBOLS: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
  UPLOAD_BINARIES: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version_encoded: ${{ steps.version_step.outputs.version_encoded }}
      version_string: ${{ steps.version_step.outputs.version_string }}

    steps:
      - name: Generate build number
        uses: mlilback/build-number@v1
        with:
          base: ${{ env.BASE_BUILD_NUMBER }}
          run-id: ${{ github.run_number }}
          # Output: ${{ env.BUILD_NUMBER }} env var

      - name: Generate Version
        id: version_step
        run: |
          echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}"

          VERSION_ENCODED="$(date '+%Y%m%d')$(printf '%06d' ${{ env.BUILD_NUMBER }})"
          VERSION_STRING="$(date '+%y.%-m.%-d')$(printf '.%d' ${{ env.BUILD_NUMBER }})"

          echo "version_encoded=$VERSION_ENCODED" >> $GITHUB_OUTPUT
          echo "version_string=$VERSION_STRING" >> $GITHUB_OUTPUT

  windows:
    needs: version
    runs-on: windows-2022

    env:
      CHECKOUT: 31.1.2
      GS_ACCESS_KEY_ID: ${{ secrets.GS_ACCESS_KEY_ID }}
      GS_KEY_BASE64: ${{ secrets.GS_KEY_BASE64 }}
      GITHUB_WORKSPACE: $GITHUB_WORKSPACE

    steps:
      - uses: actions/checkout@v4

      - name: Auth Google API
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: streamelements-core
          workload_identity_provider: ${{ vars.GCS_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ vars.GCS_SERVICE_ACCOUNT }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Clone OBS Studio
        shell: cmd
        run: |
          mkdir C:\local
          git clone --recursive https://github.com/obsproject/obs-studio.git C:\local\obs-studio
          cd /d C:\local\obs-studio
          git checkout %CHECKOUT%

      - name: Install plugin into OBS tree
        shell: cmd
        run: |
          mkdir C:\local\obs-studio\plugins\obs-streamelements-core
          xcopy "%GITHUB_WORKSPACE%\*.*" "C:\local\obs-studio\plugins\obs-streamelements-core" /S /E /I /Y
          echo add_obs_plugin(obs-streamelements-core) > C:\local\obs-studio\plugins\CMakeLists.txt

      - name: Setup GCS uploader
        shell: powershell
        run: |
          cd C:\local\obs-studio\plugins\obs-streamelements-core\CI\gcs
          [System.Text.Encoding]::UTF8.GetString(
            [System.Convert]::FromBase64String($env:GS_KEY_BASE64)
          ) | Out-File key.json
          npm install

      - name: Download BugSplat uploader
        run: |
          mkdir c:\local\bugsplat

          c:

          cd c:\local\bugsplat

          curl -sL -O https://github.com/BugSplat-Git/symbol-upload/releases/download/v10.5.0/symbol-upload-windows.exe

      - name: Generate Version
        shell: powershell
        run: |
          "#define STREAMELEMENTS_PLUGIN_VERSION ${{ needs.version.outputs.version_encoded }}" |
            Out-File C:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp

          type C:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp

          "STREAMELEMENTS_PLUGIN_VERSION=${{ needs.version.outputs.version_string }}" |
            Out-File $env:GITHUB_ENV -Append

      - name: Configure
        shell: cmd
        run: |
          copy C:\local\obs-studio\plugins\obs-streamelements-core\CMakeUserPresets.json C:\local\obs-studio\CMakeUserPresets.json
          del C:\local\obs-studio\plugins\obs-streamelements-core\CMakeUserPresets.json
          cd /d C:\local\obs-studio
          cmake --preset=windows-x64-streamelements %BUILD_OPTIONS%

      - name: Build
        shell: cmd
        run: |
          cd /d C:\local\obs-studio\build_x64
          msbuild obs-studio.sln -p:Configuration=RelWithDebInfo

      - name: Upload BugSplat Symbols
        if: ${{ env.UPLOAD_SYMBOLS }}
        shell: cmd
        run: |
          c:\local\bugsplat\symbol-upload-windows.exe ^
            -v ^
            --clientId "${{ secrets.BUGSPLAT_CLIENTID }}" ^
            --clientSecret "${{ secrets.BUGSPLAT_CLIENTSECRET }}" ^
            --application obs-streamelements-core ^
            --version "${{ needs.version.outputs.version_string }}" ^
            --database OBS_Live ^
            --directory "C:\local\obs-studio\build_x64\rundir\RelWithDebInfo\obs-plugins\64bit" ^
            --files obs-streamelements*.pdb

      - name: Package
        shell: cmd
        run: |
          cd /d C:\local\obs-studio\build_x64\rundir\RelWithDebInfo
          7z a "${{ github.workspace }}/build64_qt6.zip" .

          copy /y C:\local\obs-studio\plugins\obs-streamelements-core\streamelements\Version.generated.hpp "${{ github.workspace }}/Version.generated.hpp"

      - uses: actions/upload-artifact@v4
        with:
          name: build64
          path: '${{ github.workspace }}/build64_qt6.zip'

      - name: Upload 64bit build artifact to GCS
        if: github.event_name != 'pull_request'
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ github.workspace }}/build64_qt6.zip'
          destination: 'se-obs-builds/obs-streamelements-core/latest/windows'

      - name: Upload version header to GCS
        if: github.event_name != 'pull_request'
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ github.workspace }}/Version.generated.hpp'
          destination: 'se-obs-builds/obs-streamelements-core/latest/windows'

  macos:
    needs: version
    runs-on: macos-15

    env:
      CHECKOUT: 31.1.2
      GS_SECRET_ACCESS_KEY: ${{ secrets.GS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Auth Google API
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: streamelements-core
          workload_identity_provider: ${{ vars.GCS_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ vars.GCS_SERVICE_ACCOUNT }}

      - name: Clone OBS Studio
        run: |
          git clone --recursive https://github.com/obsproject/obs-studio.git ~/src/obs-studio
          cd ~/src/obs-studio
          git checkout $CHECKOUT

      - name: Install plugin
        run: |
          cp -R "$GITHUB_WORKSPACE" ~/src/obs-studio/plugins/obs-streamelements-core
          echo "add_obs_plugin(obs-streamelements-core)" >> ~/src/obs-studio/plugins/CMakeLists.txt

      - name: Prepare bugsplat Framework # we store it as a ZIP since on Windows the resulting paths of the unpacked archive are just way too long
        run: |
          cd ~/src/obs-studio/plugins/obs-streamelements-core/deps

          unzip BugSplat.xcframework.zip

      - name: Download BugSplat uploader
        run: |
          cd /tmp
          curl -sL -O https://github.com/BugSplat-Git/symbol-upload/releases/download/v10.5.0/symbol-upload-macos
          #cp symbol-upload-macos-intel symbol-upload-macos
          chmod +x symbol-upload-macos

      - name: Generate Version
        run: |
          echo "#define STREAMELEMENTS_PLUGIN_VERSION ${{ needs.version.outputs.version_encoded }}" \
            > ~/src/obs-studio/plugins/obs-streamelements-core/streamelements/Version.generated.hpp

          cat ~/src/obs-studio/plugins/obs-streamelements-core/streamelements/Version.generated.hpp

      - name: Build ARM64
        id: build-arm64
        run: |
          cd ~/src/obs-studio
          cmake --preset=macos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -B build_macos_arm64 \
            $BUILD_OPTIONS

          cd build_macos_arm64

          xcodebuild \
            -configuration RelWithDebInfo \
            -scheme obs-streamelements-core \
            -destination "generic/platform=macOS,name=Any Mac"

          cd ~/src/obs-studio/build_macos_arm64/plugins/obs-streamelements-core/RelWithDebInfo

          xcrun dsymutil obs-streamelements-core.plugin/Contents/MacOS/obs-streamelements-core -o obs-streamelements-core.dSYM

      - name: Build x86_64
        id: build-x86_64
        run: |
          cd ~/src/obs-studio
          cmake --preset=macos \
            -DCMAKE_OSX_ARCHITECTURES=x86_64 \
            -B build_macos_x86_64 \
            $BUILD_OPTIONS

          cd build_macos_x86_64
          xcodebuild \
            -configuration RelWithDebInfo \
            -scheme obs-streamelements-core \
            -destination "generic/platform=macOS,name=Any Mac"

          cd ~/src/obs-studio/build_macos_x86_64/plugins/obs-streamelements-core/RelWithDebInfo

          xcrun dsymutil obs-streamelements-core.plugin/Contents/MacOS/obs-streamelements-core -o obs-streamelements-core.dSYM

      - name: Upload ARM64 to BugSplat
        if: ${{ env.UPLOAD_SYMBOLS }}
        run: |
          cd ~/src/obs-studio/build_macos_arm64/plugins/obs-streamelements-core/RelWithDebInfo

          /tmp/symbol-upload-macos -v -a "obs-streamelements-core-macos" -b "OBS_Live" -i "${{ secrets.BUGSPLAT_CLIENTID }}" -s "${{ secrets.BUGSPLAT_CLIENTSECRET }}" -f "obs-streamelements-core.dSYM" -d . -v "${{ needs.version.outputs.version_encoded }}"

      - name: Upload x86_64 to BugSplat
        if: ${{ env.UPLOAD_SYMBOLS }}
        run: |
          cd ~/src/obs-studio/build_macos_x86_64/plugins/obs-streamelements-core/RelWithDebInfo

          /tmp/symbol-upload-macos -v -a "obs-streamelements-core-macos" -b "OBS_Live" -i "${{ secrets.BUGSPLAT_CLIENTID }}" -s "${{ secrets.BUGSPLAT_CLIENTSECRET }}" -f "obs-streamelements-core.dSYM" -d . -v "${{ needs.version.outputs.version_encoded }}"
      - name: Package
        run: |
          cd ~/src/obs-studio/build_macos_arm64/plugins/obs-streamelements-core/RelWithDebInfo
          7z a '${{ github.workspace }}/build_arm64.zip' .

          cd ~/src/obs-studio/build_macos_x86_64/plugins/obs-streamelements-core/RelWithDebInfo
          7z a '${{ github.workspace }}/build_x86_64.zip' .

          cp ~/src/obs-studio/plugins/obs-streamelements-core/streamelements/Version.generated.hpp '${{ github.workspace }}/Version.generated.hpp'

      - uses: actions/upload-artifact@v4
        with:
          name: macos-builds
          path: |
            build_arm64.zip
            build_x86_64.zip

      - name: Upload ARM64 build artifact to GCS
        if: github.event_name != 'pull_request'
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ github.workspace }}/build_arm64.zip'
          destination: 'se-obs-builds/obs-streamelements-core/latest/macos'

      - name: Upload x86_64 build artifact to GCS
        if: github.event_name != 'pull_request'
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ github.workspace }}/build_x86_64.zip'
          destination: 'se-obs-builds/obs-streamelements-core/latest/macos'

      - name: Upload version header to GCS
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: 'google-github-actions/upload-cloud-storage@v3'
        with:
          parent: false
          process_gcloudignore: false
          path: '${{ github.workspace }}/Version.generated.hpp'
          destination: 'se-obs-builds/obs-streamelements-core/latest/macos'

  build-uninstaller:
    needs: [ version ]
    permissions:
      contents: read
      id-token: write # lets the job mint a GitHub OIDC token for WIF
    uses: ./.github/workflows/build-obs-streamelements-uninstaller.yml
  build-installer:
    needs: [ version, build-uninstaller, windows, macos ]
    permissions:
      contents: read
      id-token: write # lets the job mint a GitHub OIDC token for WIF
    uses: ./.github/workflows/build-obs-streamelements-installer.yml
  tag-master-commit:
    if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
    needs: [version, windows, macos, build-uninstaller, build-installer]
    runs-on: ubuntu-latest

    steps:
      - name: Tag master commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ needs.version.outputs.version_string }}"
