name: Release Signed Binary

concurrency:
  group: ${{ github.workflow }}-${{ case(startsWith(github.event.head_commit.message, '[WORKFLOW-AUTOMATION]'), 'automation', github.event.pull_request.number || github.ref) }}
  cancel-in-progress: ${{ !startsWith(github.event.head_commit.message, '[WORKFLOW-AUTOMATION]') }}

permissions:
  contents: read     # lets GITHUB_TOKEN push tags
  id-token: write    # lets the job mint a GitHub OIDC token for WIF

on:
  workflow_dispatch:
    inputs:
      from:
        type: environment
        required: true
      to:
        type: environment
        required: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: |
          echo "${{ github.event.inputs.from }} -> ${{ github.event.inputs.to }}"
